services:
  - type: web
    name: hms-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "True"
      - key: ALLOWED_HOSTS
        value: "hospital-management-system-rfqk.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: hms-db
          property: connectionString
    databases:
      - name: hms-db
        databaseName: hms
        user: hms

  - type: web
    name: hms-frontend
    env: static
    buildCommand: cd frontend && npm ci && npm run build
    staticPublish: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://hospital-management-system-rfqk.onrender.com
      - key: NODE_VERSION
        value: "18"
