# Generated by Django 6.0.2 on 2026-02-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctorspecialty_medication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_symptoms',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_warnings',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='patient',
            name='lab_reports',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='INR', max_length=8),
        ),
    ]
